config/routes.rb
Rails.application.routes.draw do

  resources :restaurants

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'restaurants#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
        user ||= User.new
    if user.restaurant_manager?
        can :manage, :all
    elsif user.kitchen_manager?
        can :create, Restaurant
    else
        can :read, :all
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/drink.rb
class Drink < ActiveRecord::Base
	belongs_to :restaurant

  validates :name, :price, :image, presence: true
  do_not_validate_attachment_file_type :image

  has_attached_file :image, styles: { :large => "600x600#", :medium => "300x300#", :thumb => "100x100#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/food.rb
class Food < ActiveRecord::Base
	belongs_to :restaurant

  validates :name, :price, :image, presence: true
  do_not_validate_attachment_file_type :image

  has_attached_file :image, styles: { :large => "600x600#", :medium => "300x300#", :thumb => "100x100#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	belongs_to :user
	has_many :foods, dependent: :destroy
	has_many :drinks, dependent: :destroy

	accepts_nested_attributes_for :foods,
  															reject_if: proc { |attributes| attributes['name'].blank? },
  															allow_destroy: true
 	accepts_nested_attributes_for :drinks,
  															reject_if: proc { |attributes| attributes['name'].blank? },
  															allow_destroy: true

  # attr_accessor :ip_address
  # geocoded_by :ip_address,
  #   :latitude => :latitude, :longitude => :longitude
  # geocoded_by :address
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode

  # validates :name, :address, :category, :latitude, :longitude, :image, presence: true
  validates :name, :category, :image, presence: true

	has_attached_file :image, styles: { :large => "600x600#", :medium => "300x300#", :thumb => "150x150#" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  # def self.search(search)
  #   if search
  #     Restaurant.where('name LIKE ?', "%#{search}%")
  #   else
  #     Restaurant.all
  #   end
  # end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauth_providers => [:facebook]

  has_many :restaurants

  # def self.sign_in_from_omniauth(auth)
  #   find_by(provider: auth['provider'], uid: auth['uid']) || create_user_from_omniauth(auth)
  # end

  # def self.create_user_from_omniauth(auth)
  #   create(
  #       provider: auth['provider'],
  #       uid: auth['uid'],
  #       name: auth['info']['name']
  #     )
  # end

  def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
      end
  end

  # def self.new_with_session(params, session)
  #   if session["devise.user_attributes"]
  #     new(session["devise.user_attributes"], without_protection: true) do |user|
  #       user.attributes = params
  #       user.valid?
  #     end
  #   else
  #     super
  #   end
  # end

  # def password_required?
  #   super && provider.blank?
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	rescue_from CanCan::AccessDenied do |exception|
		redirect_to root_url, :alert => exception.message
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		
	end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
  	@restaurants = Restaurant.all.page(params[:page]).per(9)
    @restaurants = Restaurant.where(["name LIKE ?", "%#{params[:search]}%"]).page(params[:page]).per(9)
    @restaurant = Restaurant.new
    @food = Food.new


  	respond_to do |format|
      format.html { render 'index' }
      format.json { render json: @restaurants}
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @hash = Gmaps4rails.build_markers(@restaurant) do |restaurant, marker|
      marker.lat restaurant.latitude
      marker.lng restaurant.longitude
      marker.infowindow restaurant.address
      marker.picture({
       "url" => "http://www.hoyer-group.com/fileadmin/templates/hoyer_group/skeleton/img/gmaps-marker.png",
       "width" =>  32,
       "height" => 32})
      marker.json({ name: restaurant.name })
    end
  end

  def new
    # @restaurant = Restaurant.new
    @restaurant = current_user.restaurants.build
  end

  def create
    # @restaurant = Restaurant.new(restaurant_params)
    
    @restaurant = current_user.restaurants.build(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant, notice: "Successfully created new restaurant"
    else
      render 'new'
    end

  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])

    if @restaurant.update(restaurant_params)
      redirect_to @restaurant
    else
      render 'edit'
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to root_path, notice: "Successfully deleted restaurant"
  end

  private
  	def restaurant_params
  		params.require(:restaurant).permit(:name, :address, :category, :latitude, :longitude, :image, foods_attributes: [:id, :image, :name, :price, :_destroy], drinks_attributes: [:id, :image, :name, :price, :_destroy])
  	end

    def find_restaurant
      @restaurant = Restaurant.find(params[:id])
    end
end

app/controllers/sessions_controller.rb
# class SessionsController < ApplicationController
#   def create
#     auth = request.env["omniauth.auth"]
#     session[:omniauth] = auth.expect('extra')
#     user = User.sign_in_from_omniauth(auth)
#     session[:user_id] = user.id
#     redirect_to root_url, notice: "Sign in!"
#   end

#   def destroy
#     session[:user_id] = nil
#     session[:omniauth] = nil
#     redirect_to root_url, notice: "Sign out!"
#   end
# end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.erb
<!-- <body class="bground" style="background-image: linear-gradient(
											                rgba(0, 0, 0, 0.45), 
											                rgba(0, 0, 0, 0.45)
											              ), 
									url('https://download.unsplash.com/31/RpgvvtYAQeqAIs1knERU_vegetables.jpg')"> -->
<body>

<div class="page_wrapper">
<p id="notice"><%= notice %></p>
	<div class="container-fluid">
	  <div class="row">
	  	<div class="col-md-12 col-md-offset-1">
				<h1>Melody</h1>
				<h2>Order your meal anywhere</h2>

				<div class="btn-group">
				  <button class="btn btn-default btn-lg dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				    Select type <span class="caret"></span>
				  </button>
				  <ul class="dropdown-menu">
				    <li><a href="#">Location</a></li>
				    <li><a href="#">Categories</a></li>
				  </ul>
				</div>
			</div>
		</div>
	</div>
</div>

</body>

app/views/layouts/_header.html.erb
<!-- Navigation -->
<header>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="<%= root_path %>">Home</a>
          </div>
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-right">
                  <li>
                      <%= link_to "Restaurant", "#" %>
                  </li>
                  <li>
                      <%= link_to "About", "#" %>
                  </li>
                  <li>
                      <%= link_to "Contact", "#" %>
                  </li>
                  <% if user_signed_in? %>
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        User Menu <b class="caret"></b>
                      </a>
                      <ul class="dropdown-menu">
                        <li>
                          <%= link_to "Create Restaurant", new_restaurant_path %>
                        </li>
                        <li>
                          <%= link_to "Log Out", destroy_user_session_path, :method => :delete %>
                        </li>
                      </ul>
                    </li>
                  <% else %>
                    <li>
                      <%= link_to "Log In", new_user_session_path %>
                    </li>
                  <% end %>
              </ul>
          </div>
          <!-- /.navbar-collapse -->
      </div>
      <!-- /.container -->
  </nav>
</header>

app/views/layouts/_shim.html.erb
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Melody</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <%= render 'layouts/shim' %>
</head>

<body>
<%= render 'layouts/header' %>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

<%= render 'layouts/footer' %>
</body>
</html>

app/views/restaurants/_add_drink_form.html.erb
<%= simple_form_for @restaurant, html: { multipart: true } do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="errors">
      <p>
        <%= @restaurant.errors.count %>
        Prevented this log from saving
      </p>
      <ul>
        <% @restaurant.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="panel-body">
    <%= f.submit "Submit Drink", class: "btn btn-primary" %>
  </div>

  <div id="drinks">
    <%= f.simple_fields_for :drinks do |drink| %>
      <%= render 'drink_fields', :f => drink %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'Add Drink', f, :drinks, class: "btn btn-primary add-button" %>
    </div>
  </div>

<% end %>

app/views/restaurants/_add_food_form.html.erb
<%= simple_form_for @restaurant, html: { multipart: true } do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="errors">
      <p>
        <%= @restaurant.errors.count %>
        Prevented this log from saving
      </p>
      <ul>
        <% @restaurant.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="panel-body">
    <%= f.submit "Submit Food", class: "btn btn-primary" %>
  </div>

  <div id="foods">
    <%= f.simple_fields_for :foods do |food| %>
      <%= render 'food_fields', :f => food %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'Add More Food', f, :foods, class: "btn btn-primary add-button" %>
    </div>
  </div>

<% end %>

app/views/restaurants/_drink_fields.html.erb
<div class="nested-fields">
  <%= f.input :name, input_html: { class: 'form-input form-control' } %>
  <%= f.input :price %>
  <%= f.file_field :image, input_html: { class: 'form-input form-control' } %>
  <%= link_to_remove_association "Remove Drink", f, class: "form-button btn btn-danger" %>
</div>

app/views/restaurants/_food_fields.html.erb
<div class="nested-fields">
  <%= f.input :name, input_html: { class: 'form-input form-control' } %>
  <%= f.input :price %>
  <%= f.file_field :image, input_html: { class: 'form-input form-control' } %>
  <%= link_to_remove_association "Remove Food", f, class: "form-button btn btn-danger" %>
</div>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant, html: { multipart: true } do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="errors">
      <p>
        <%= @restaurant.errors.count %>
        Prevented this log from saving
      </p>
      <ul>
        <% @restaurant.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="panel-body">
    <%= f.input :name, input_html: { class: 'form-control' } %>
    <%= f.input :address, input_html: { class: 'form-control' } %>
    <%= f.input :category, input_html: { class: 'form-control' } %>
    <%= f.input :latitude, input_html: { class: 'form-control' } %>
    <%= f.input :longitude, input_html: { class: 'form-control' } %>
    <%= f.input :image, input_html: { class: 'form-control' } %>
    <%= f.submit "Create Restaurant", class: "btn btn-primary" %>
  </div>

  <div id="foods">
    <%= f.simple_fields_for :foods do |food| %>
      <%= render 'food_fields', :f => food %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'Add Food', f, :foods, class: "btn btn-default add-button" %>
    </div>
  </div>

  <div id="drinks">
    <%= f.simple_fields_for :drinks do |drink| %>
      <%= render 'drink_fields', :f => drink %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'Add Drink', f, :drinks, class: "btn btn-default add-button" %>
    </div>
  </div>

<% end %>

app/views/restaurants/edit.html.erb
<div class="page_wrapper">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">

        <h2>Edit Restaurant</h2>
        <%= render 'form' %>

      </div>
    </div>
  </div>
</div>

app/views/restaurants/index.html.erb
<div class="page_wrapper">
	<div class="container-fluid">
	  <div class="row">
	  	<div class="col-md-11 col-md-offset-1">

          <%= form_tag restaurants_path, :method => 'get'  do %>
           <%= text_field_tag :search, params[:search]%>
           <%= submit_tag "Search" %>
          <% end %>


            <div class="table-responsive">
              <table class="table table-hover borderless" id="table">
                <thead>
                  <tr>
                    <td>Restaurant Logo</td>
                    <td>Restaurant Name</td>
                    <td>Category</td>
                  </tr>
                </thead>

                <% @restaurants.each do |restaurant| %>
                  <tr>
                    <td> <%= image_tag restaurant.image.url(:thumb), class: "recipe_image" %> </td>
                    <td> <%= link_to restaurant.name, restaurant %> </td>
                    <td> <%= link_to restaurant.category, restaurant %> </td>
                  </tr>
                <% end %>


              </table>
            </div>


          <%= paginate @restaurants,:theme => 'twitter-bootstrap-3', :pagination_class => "pagination-sm" %>

			</div>
		</div>
	</div>
</div>

app/views/restaurants/new.html.erb
<div class="page_wrapper">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">

        <h2>Create Restaurant</h2>
        <%= render 'form' %>

      </div>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/trunk/richmarker/src/richmarker-compiled.js' type='text/javascript'></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script>

<div class="page_wrapper">
  <div class="row">
    <div class="col-md-2 col-md-offset-2">
      <%= image_tag @restaurant.image.url(:thumb), class: "recipe_image" %>
    </div>
    <div class="col-md-6">
      <div>
        <h1>
          <%= @restaurant.name %>
        </h1>
        <h3>
          <%= @restaurant.address %>
          <%= @restaurant.latitude %>
          <%= @restaurant.longitude %>
        </h3>

        <%= link_to "Back", root_path, class: "btn btn-default btn-xs" %>
        <% if user_signed_in? %>
          <%= link_to "Edit", edit_restaurant_path, class: "btn btn-default btn-xs" %>
          <%= link_to "Delete", restaurant_path, method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-default btn-xs" %>
        <% end %>

      </div>
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="col-md-6">
      <div id="ingredients">
        <h2>Food</h2>

          <% if user_signed_in? %>
            <!-- Button trigger for food modal -->
            <button type="button" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#addFoodModal">
              Add Food
            </button>
          <% end %>

          <!-- Food Modal -->
          <%= form_for(@restaurant) do |f| %>
            <div class="modal fade" id="addFoodModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
              <div class="modal-dialog" role="document">
                <div class="modal-content">

                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Add Food</h4>
                  </div>

                  <div class="modal-body">
                    <%= render 'add_food_form' %>        
                  </div>

                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <%= submit_tag "Save", class: "btn btn-primary"%>
                  </div>

                </div>
              </div>
            </div>
          <% end %>



        <ul>
          <% @restaurant.foods.each do |food| %>
            <li>
              <%= food.name %>
              <%= food.price %>
              <%= image_tag food.image.url(:thumb) %>
            </li>
          <% end %>
        </ul>

      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div id="ingredients">
        <h2>Drink</h2>

          <% if user_signed_in? %>
            <!-- Button trigger for drink modal -->
            <button type="button" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#addDrinkModal">
              Add Drink
            </button>
          <% end %>

            

            <!-- Drink Modal -->
            <%= form_for(@restaurant) do |f| %>
              <div class="modal fade" id="addDrinkModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">

                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      <h4 class="modal-title" id="myModalLabel">Add Food</h4>
                    </div>

                    <div class="modal-body">
                      <%= render 'add_drink_form' %>        
                    </div>

                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                      <%= submit_tag "Save", class: "btn btn-primary"%>
                    </div>

                  </div>
                </div>
              </div>
            <% end %>

        <ul>
          <% @restaurant.drinks.each do |drink| %>
            <li>
              <%= image_tag drink.image.url(:thumb) %>
              <%= drink.name %>
              <%= drink.price %>
            </li>
          <% end %>
        </ul>

      </div>
    </div>
  </div>

  <div style='width: 800px;'>
    <div id="map" style='width: 800px; height: 400px;'></div>
  </div>

  <script type="text/javascript">
   buildMap(<%=raw @hash.to_json %>);
  </script>


  <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@restaurant.latitude}%2C#{@restaurant.longitude}" %>
</div>

app/views/users/finish_signup.html.erb
<div id="add-email" class="container">
  <h1>Add Email</h1>
  <%= form_for(current_user, :as => 'user', :url => finish_signup_path(current_user), :html => { role: 'form'}) do |f| %>
    <% if @show_errors && current_user.errors.any? %>
      <div id="error_explanation">
        <% current_user.errors.full_messages.each do |msg| %>
          <%= msg %><br>
        <% end %>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :email %>
      <div class="controls">
        <%= f.text_field :email, :autofocus => true, :value => '', class: 'form-control input-lg', placeholder: 'Example: email@me.com' %>
        <p class="help-block">Please confirm your email address. No spam.</p>
      </div>
    </div>
    <div class="actions">
      <%= f.submit 'Continue', :class => 'btn btn-primary' %>
    </div>
  <% end %>
</div>